name: feddaa
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.4
  - torchvision=0.19
  - torchaudio=2.4
  - pytorch-cuda=11.8
  - numpy=1.26
  - pandas=2.2
  - scipy=1.13
  - scikit-learn=1.5
  - scikit-image=0.24
  - matplotlib=3.9
  - pillow=11.0
  - tqdm=4.66
  - tensorboard=2.18
  - opencv=4.7
  - wand=0.6.10
  - pyyaml=6.0.2
  - requests=2.32
  - networkx=3.2
  - cvxpy=1.6
  - pip
